//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edimsha.WPF.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Edimsha.WPF.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always include when replacing.
        /// </summary>
        internal static string always_include_when_replacing {
            get {
                return ResourceManager.GetString("always_include_when_replacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application started.
        /// </summary>
        internal static string application_started {
            get {
                return ResourceManager.GetString("application_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By default same folder edimsha_Imagename.png.
        /// </summary>
        internal static string by_default_same_folder_edimsha_imagename_png {
            get {
                return ResourceManager.GetString("by_default_same_folder_edimsha_imagename_png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change edimsha to:.
        /// </summary>
        internal static string change_edimsha_to {
            get {
                return ResourceManager.GetString("change_edimsha_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression in%:.
        /// </summary>
        internal static string compression_in_percentage {
            get {
                return ResourceManager.GetString("compression_in_percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converter.
        /// </summary>
        internal static string converter {
            get {
                return ResourceManager.GetString("converter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all paths.
        /// </summary>
        internal static string delete_all_paths {
            get {
                return ResourceManager.GetString("delete_all_paths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete item.
        /// </summary>
        internal static string delete_item {
            get {
                return ResourceManager.GetString("delete_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete paths on exit.
        /// </summary>
        internal static string delete_paths_on_exit {
            get {
                return ResourceManager.GetString("delete_paths_on_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted resolution!.
        /// </summary>
        internal static string deleted_resolution {
            get {
                return ResourceManager.GetString("deleted_resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag the images or folder to edit.
        /// </summary>
        internal static string drag_the_images_or_folder_to_edit {
            get {
                return ResourceManager.GetString("drag_the_images_or_folder_to_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edimsha_ (omitted if the output folder is different).
        /// </summary>
        internal static string edimsha_omitted_if_the_output_folder_is_different {
            get {
                return ResourceManager.GetString("edimsha_omitted_if_the_output_folder_is_different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        internal static string editor {
            get {
                return ResourceManager.GetString("editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving editor paths.
        /// </summary>
        internal static string error_saving_editor_paths {
            get {
                return ResourceManager.GetString("error_saving_editor_paths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height (px):.
        /// </summary>
        internal static string height_px {
            get {
                return ResourceManager.GetString("height_px", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height (px) (Y):.
        /// </summary>
        internal static string heightpxy {
            get {
                return ResourceManager.GetString("heightpxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image files.
        /// </summary>
        internal static string image_files {
            get {
                return ResourceManager.GetString("image_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iterate folders and subfolders.
        /// </summary>
        internal static string iterate_folders_and_subfolders {
            get {
                return ResourceManager.GetString("iterate_folders_and_subfolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep original resolution.
        /// </summary>
        internal static string keep_original_resolution {
            get {
                return ResourceManager.GetString("keep_original_resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List options:.
        /// </summary>
        internal static string list_options {
            get {
                return ResourceManager.GetString("list_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load resolution.
        /// </summary>
        internal static string load_resolution {
            get {
                return ResourceManager.GetString("load_resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string mode {
            get {
                return ResourceManager.GetString("mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize image.
        /// </summary>
        internal static string optimize_image {
            get {
                return ResourceManager.GetString("optimize_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output folder:.
        /// </summary>
        internal static string output_folder {
            get {
                return ResourceManager.GetString("output_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output resolution:.
        /// </summary>
        internal static string output_resolution {
            get {
                return ResourceManager.GetString("output_resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string quit {
            get {
                return ResourceManager.GetString("quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with original image.
        /// </summary>
        internal static string replace_with_original_image {
            get {
                return ResourceManager.GetString("replace_with_original_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset complete!.
        /// </summary>
        internal static string reset_completed {
            get {
                return ResourceManager.GetString("reset_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution saved!.
        /// </summary>
        internal static string resolution_saved {
            get {
                return ResourceManager.GetString("resolution_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolutions:.
        /// </summary>
        internal static string resolutions {
            get {
                return ResourceManager.GetString("resolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolutions used.
        /// </summary>
        internal static string resolutions_used {
            get {
                return ResourceManager.GetString("resolutions_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save resolution.
        /// </summary>
        internal static string save_resolution {
            get {
                return ResourceManager.GetString("save_resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search update.
        /// </summary>
        internal static string search_update {
            get {
                return ResourceManager.GetString("search_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select files.
        /// </summary>
        internal static string select_files {
            get {
                return ResourceManager.GetString("select_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder.
        /// </summary>
        internal static string select_folder {
            get {
                return ResourceManager.GetString("select_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select images.
        /// </summary>
        internal static string select_images {
            get {
                return ResourceManager.GetString("select_images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send logs (0 errors).
        /// </summary>
        internal static string send_logs_0_errors {
            get {
                return ResourceManager.GetString("send_logs_0_errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The option could not be saved.
        /// </summary>
        internal static string the_option_could_not_be_saved {
            get {
                return ResourceManager.GetString("the_option_could_not_be_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resolution already exists!.
        /// </summary>
        internal static string the_resolution_already_exists {
            get {
                return ResourceManager.GetString("the_resolution_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width (px):.
        /// </summary>
        internal static string width_px {
            get {
                return ResourceManager.GetString("width_px", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width (px) (Y):.
        /// </summary>
        internal static string widthpxx {
            get {
                return ResourceManager.GetString("widthpxx", resourceCulture);
            }
        }
    }
}
