//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edimsha.WPF.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Edimsha.WPF.Lang.Resources.es", typeof(Resources_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siempre incluir al remplazar.
        /// </summary>
        internal static string always_include_when_replacing {
            get {
                return ResourceManager.GetString("always_include_when_replacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por defecto misma carpeta edimsha_nombreImagen.png.
        /// </summary>
        internal static string by_default_same_folder_edimsha_imagename_png {
            get {
                return ResourceManager.GetString("by_default_same_folder_edimsha_imagename_png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar edimsha por:.
        /// </summary>
        internal static string change_edimsha_to {
            get {
                return ResourceManager.GetString("change_edimsha_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compresion en %:.
        /// </summary>
        internal static string compression_in_percentage {
            get {
                return ResourceManager.GetString("compression_in_percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversor.
        /// </summary>
        internal static string converter {
            get {
                return ResourceManager.GetString("converter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar todas las rutas.
        /// </summary>
        internal static string delete_all_paths {
            get {
                return ResourceManager.GetString("delete_all_paths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar ruta.
        /// </summary>
        internal static string delete_item {
            get {
                return ResourceManager.GetString("delete_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar rutas al salir.
        /// </summary>
        internal static string delete_paths_on_exit {
            get {
                return ResourceManager.GetString("delete_paths_on_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrastra las imagenes o carpeta a editar.
        /// </summary>
        internal static string drag_the_images_or_folder_to_edit {
            get {
                return ResourceManager.GetString("drag_the_images_or_folder_to_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edimsha_ (omitido si la carpeta de salida es diferente).
        /// </summary>
        internal static string edimsha_omitted_if_the_output_folder_is_different {
            get {
                return ResourceManager.GetString("edimsha_omitted_if_the_output_folder_is_different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        internal static string editor {
            get {
                return ResourceManager.GetString("editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alto (px):.
        /// </summary>
        internal static string height_px {
            get {
                return ResourceManager.GetString("height_px", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivos de imagen.
        /// </summary>
        internal static string image_files {
            get {
                return ResourceManager.GetString("image_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciado.
        /// </summary>
        internal static string initiated {
            get {
                return ResourceManager.GetString("initiated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantener resolución original.
        /// </summary>
        internal static string keep_original_resolution {
            get {
                return ResourceManager.GetString("keep_original_resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modo.
        /// </summary>
        internal static string mode {
            get {
                return ResourceManager.GetString("mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimizar imagen.
        /// </summary>
        internal static string optimize_image {
            get {
                return ResourceManager.GetString("optimize_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carpeta de salida:.
        /// </summary>
        internal static string output_folder {
            get {
                return ResourceManager.GetString("output_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolución de salida:.
        /// </summary>
        internal static string output_resolution {
            get {
                return ResourceManager.GetString("output_resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        internal static string quit {
            get {
                return ResourceManager.GetString("quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remplazar imagen por original.
        /// </summary>
        internal static string replace_with_original_image {
            get {
                return ResourceManager.GetString("replace_with_original_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetear.
        /// </summary>
        internal static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resoluciones usadas.
        /// </summary>
        internal static string resolutions_used {
            get {
                return ResourceManager.GetString("resolutions_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar actualización.
        /// </summary>
        internal static string search_update {
            get {
                return ResourceManager.GetString("search_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar archivos.
        /// </summary>
        internal static string select_files {
            get {
                return ResourceManager.GetString("select_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar carpeta.
        /// </summary>
        internal static string select_folder {
            get {
                return ResourceManager.GetString("select_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona imágenes.
        /// </summary>
        internal static string select_images {
            get {
                return ResourceManager.GetString("select_images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar logs (0 errores).
        /// </summary>
        internal static string send_logs_0_errors {
            get {
                return ResourceManager.GetString("send_logs_0_errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parar.
        /// </summary>
        internal static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancho (px):.
        /// </summary>
        internal static string width_px {
            get {
                return ResourceManager.GetString("width_px", resourceCulture);
            }
        }
    }
}
